// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqxXf0YMORPrz4w9RAavKQtMFR7xrmaw',
    appId: '1:601499410912:web:66e7220b7385d231058b85',
    messagingSenderId: '601499410912',
    projectId: 'chat-app-29616',
    authDomain: 'chat-app-29616.firebaseapp.com',
    storageBucket: 'chat-app-29616.appspot.com',
    measurementId: 'G-HHDQEPW191',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQ2_HHnqYWIRZDsAPbcUC6dHQEvYOdGw',
    appId: '1:601499410912:android:8c77122a462ac3b8058b85',
    messagingSenderId: '601499410912',
    projectId: 'chat-app-29616',
    storageBucket: 'chat-app-29616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlsUew-ZTEEgHJ-PgYEaQdK0T2kn5RIJE',
    appId: '1:601499410912:ios:1a3e908ef25be4be058b85',
    messagingSenderId: '601499410912',
    projectId: 'chat-app-29616',
    storageBucket: 'chat-app-29616.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlsUew-ZTEEgHJ-PgYEaQdK0T2kn5RIJE',
    appId: '1:601499410912:ios:2430c3b7e892cca2058b85',
    messagingSenderId: '601499410912',
    projectId: 'chat-app-29616',
    storageBucket: 'chat-app-29616.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
